runtime: python27
threadsafe: true

skip_files:
  - ^naonedia-app/.*
  - ^LICENSE
  - ^README.md
  - ^.gitignore

handlers:
- url: /
  static_files: gc/index.html
  upload: gc/index.html
 
- url: /(.*)
  static_files: gc/\1
  upload: gc/(.*)
